name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: world hello
      run: cd ./world_hello
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
